spring.application.name=LibraryDackend
spring.datasource.url=jdbc:mysql://localhost:3306/Library
spring.datasource.username=root
spring.datasource.password=7072
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080